// Code generated by sqlc. DO NOT EDIT.

package kprdb

import (
	"database/sql"
	"time"

	"github.com/jackc/pgtype"
)

type KeyperDecryptionKey struct {
	EpochID       []byte
	KeyperIndex   sql.NullInt64
	DecryptionKey []byte
}

type KeyperDecryptionKeyShare struct {
	EpochID            []byte
	KeyperIndex        int64
	DecryptionKeyShare []byte
}

type KeyperDecryptionTrigger struct {
	EpochID []byte
}

type KeyperMetaInf struct {
	Key   string
	Value string
}

type KeyperPuredkg struct {
	Eon     pgtype.Numeric
	Puredkg []byte
}

type KeyperTendermintBatchConfig struct {
	ConfigIndex int32
	Height      int64
	Keypers     []string
	Threshold   int32
}

type KeyperTendermintSyncMetum struct {
	CurrentBlock        int64
	LastCommittedHeight int64
	SyncTimestamp       time.Time
}
