// Code generated by sqlc. DO NOT EDIT.

package kprdb

import (
	"database/sql"
)

type KeyperDecryptionKey struct {
	EpochID       []byte
	KeyperIndex   sql.NullInt64
	DecryptionKey []byte
}

type KeyperDecryptionKeyShare struct {
	EpochID            []byte
	KeyperIndex        int64
	DecryptionKeyShare []byte
}

type KeyperDecryptionTrigger struct {
	EpochID []byte
}

type KeyperMetaInf struct {
	Key   string
	Value string
}
