// Code generated by sqlc. DO NOT EDIT.

package dcrdb

import ()

type DecryptorAggregatedSignature struct {
	EpochID         []byte
	SignedHash      []byte
	SignersBitfield []byte
	Signature       []byte
}

type DecryptorCipherBatch struct {
	EpochID      []byte
	Transactions [][]byte
}

type DecryptorDecryptionKey struct {
	EpochID []byte
	Key     []byte
}

type DecryptorDecryptionSignature struct {
	EpochID         []byte
	SignedHash      []byte
	SignersBitfield []byte
	Signature       []byte
}

type DecryptorDecryptorIdentity struct {
	Address      string
	BlsPublicKey []byte
}

type DecryptorDecryptorSetMember struct {
	StartEpochID []byte
	Index        int32
	Address      string
}

type DecryptorEonPublicKey struct {
	StartEpochID []byte
	EonPublicKey []byte
}

type DecryptorKeyperSet struct {
	StartEpochID []byte
	Keypers      []string
	Threshold    int32
}

type DecryptorMetaInf struct {
	Key   string
	Value string
}
