// Code generated by sqlc. DO NOT EDIT.

package dcrdb

import (
	"database/sql"
)

type DecryptorCipherBatch struct {
	EpochID      []byte
	Transactions [][]byte
}

type DecryptorDecryptionKey struct {
	EpochID []byte
	Key     []byte
}

type DecryptorDecryptionSignature struct {
	EpochID     []byte
	SignedHash  []byte
	SignerIndex int64
	Signature   []byte
}

type DecryptorDecryptorIdentity struct {
	Address      string
	BlsPublicKey []byte
}

type DecryptorDecryptorSetMember struct {
	StartEpochID []byte
	Index        int32
	Address      sql.NullString
}

type DecryptorEonPublicKey struct {
	StartEpochID []byte
	EonPublicKey []byte
}

type DecryptorKeyperSet struct {
	StartEpochID []byte
	Keypers      []string
	Threshold    int32
}

type DecryptorMetaInf struct {
	Key   string
	Value string
}
