// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package chainobsdb

import (
	"context"
)

type Querier interface {
	GetChainCollator(ctx context.Context, activationBlockNumber int64) (ChainCollator, error)
	InsertChainCollator(ctx context.Context, arg InsertChainCollatorParams) error
}

var _ Querier = (*Queries)(nil)
