// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"context"
)

type Querier interface {
	GetMeta(ctx context.Context, key string) (string, error)
	InsertMeta(ctx context.Context, arg InsertMetaParams) error
}

var _ Querier = (*Queries)(nil)
