// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package chainobsdb

import (
	"context"
)

type Querier interface {
	GetKeyperSet(ctx context.Context, activationBlockNumber int64) (KeyperSet, error)
	GetKeyperSetByKeyperConfigIndex(ctx context.Context, keyperConfigIndex int64) (KeyperSet, error)
	InsertKeyperSet(ctx context.Context, arg InsertKeyperSetParams) error
}

var _ Querier = (*Queries)(nil)
