[env]
# Keys and addresses of accounts pre-funded by Anvil
ANVIL_KEY_0 = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
ANVIL_ADDRESS_0 = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
ANVIL_KEY_1 = "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"
ANVIL_ADDRESS_1 = "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
ANVIL_KEY_2 = "0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a"
ANVIL_ADDRESS_2 = "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"

DATA_DIR = "./data/"
GENERATED_DIR = "./generated/"
STATIC_DIR = "./static/"

DEPLOY_KEY = "{{env.ANVIL_KEY_0}}"
ETHEREUM_BLOCK_TIME = "1"
ETHEREUM_CHAIN_ID = "31337"
NUM_KEYPERS = "4"
INITIAL_KEYPER_SET_INDICES = "0,1,2"
INITIAL_THRESHOLD = "2"
ACTIVATION_DELTA = "10"
DKG_RESULT_POLL_INTERVAL = "1"
DECRYPTION_KEY_POLL_INTERVAL = "1"
DECRYPTION_TRIGGER_TIMESTAMP_DELTA = "10"
SHUTTERMINT_BLOCK_TIME = "1"
SHUTTERMINT_DKG_PHASE_LENGTH = "10"
SHUTTERMINT_START_BLOCK_DELTA = "200"
SHUTTERMINT_RPC_PORT = "26657"
SHUTTERMINT_P2P_PORT = "26656"
DEPLOYMENT_TYPE = "service"  # "gnosis" or "service"
