// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

type Commitment struct {
	TxHashes            []string
	ProviderAddress     string
	CommitmentSignature string
	CommitmentDigest    string
	BlockNumber         int64
}

type CommittedTransaction struct {
	Eon              int64
	IdentityPreimage string
	BlockNumber      int64
	TxHash           string
}

type ProviderRegistryEvent struct {
	BlockNumber     int64
	BlockHash       []byte
	TxIndex         int64
	LogIndex        int64
	ProviderAddress string
	BlsKeys         [][]byte
}

type ProviderRegistryEventsSyncedUntil struct {
	EnforceOneRow bool
	BlockHash     []byte
	BlockNumber   int64
}
