// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package database

import ()

type TransactionSubmittedEvent struct {
	BlockNumber    int64
	BlockHash      []byte
	TxIndex        int64
	LogIndex       int64
	Eon            int64
	IdentityPrefix []byte
	Sender         string
	GasLimit       int64
}

type TransactionSubmittedEventsSyncedUntil struct {
	EnforceOneRow bool
	BlockNumber   int64
}
