// Code generated by "stringer -type=Environment -output environment_string.gen.go"; DO NOT EDIT.

package p2p

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Staging-0]
	_ = x[Production-1]
	_ = x[Local-2]
}

const _Environment_name = "StagingProductionLocal"

var _Environment_index = [...]uint8{0, 7, 17, 22}

func (i Environment) String() string {
	if i < 0 || i >= Environment(len(_Environment_index)-1) {
		return "Environment(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Environment_name[_Environment_index[i]:_Environment_index[i+1]]
}
