// Code generated by sqlc. DO NOT EDIT.

package cltrdb

import ()

type CollatorCipherBatch struct {
	EpochID      []byte
	Transactions [][]byte
}

type CollatorDecryptionTrigger struct {
	EpochID   []byte
	BatchHash []byte
}

type CollatorMetaInf struct {
	Key   string
	Value string
}

type CollatorTransaction struct {
	TxID        []byte
	EpochID     []byte
	EncryptedTx []byte
}
