// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package cltrdb

import (
	"database/sql"
)

type DecryptionKey struct {
	EpochID       []byte
	DecryptionKey []byte
}

type DecryptionTrigger struct {
	EpochID   []byte
	BatchHash []byte
}

type EonPublicKeyCandidate struct {
	Hash                  []byte
	EonPublicKey          []byte
	ActivationBlockNumber int64
	KeyperConfigIndex     int64
	Eon                   int64
	Confirmed             bool
}

type EonPublicKeyVote struct {
	Hash              []byte
	Sender            string
	Signature         []byte
	Eon               int64
	KeyperConfigIndex int64
}

type MetaInf struct {
	Key   string
	Value string
}

type NextBatch struct {
	EnforceOneRow bool
	EpochID       []byte
	L1BlockNumber int64
}

type Transaction struct {
	TxHash  []byte
	ID      sql.NullInt32
	EpochID []byte
	TxBytes []byte
}
