version: 2.1

# CircleCI dynamic configuration file, see
# https://circleci.com/docs/2.0/dynamic-config/

setup: true

orbs:
  continuation: circleci/continuation@0.3.1

executors:
  cimg-base:
    docker:
      - image: cimg/base:2023.05

jobs:
  gen:
    executor: cimg-base
    working_directory: ~/src/.circleci
    steps:
      - checkout:
          path: ~/src
      - restore_cache:
          key: gen-clj-v17
      - run:
          name: Install babashka
          command: |
            if [[ -e ~/bin/bb ]]; then
              echo "babashka already installed"
            else
              curl -sL https://raw.githubusercontent.com/babashka/babashka/master/install -o ~/install-bb
              mkdir -p ~/bin
              bash ~/install-bb --version 1.3.179 --dir ~/bin
            fi
      - run:
          name: Generate continuation config
          command: |
            ~/bin/bb -gen-ci
      - save_cache:
          key: gen-clj-v17
          paths:
            - ~/bin/
      - continuation/continue:
          configuration_path: continue-generated.yml

workflows:
  gen:
    jobs:
      - gen:
          filters:
            tags:
              only: /^.*$/
