// Code generated by sqlc. DO NOT EDIT.

package snpdb

import ()

type DecryptionKey struct {
	EpochID []byte
	Key     []byte
}

type EonPublicKey struct {
	EonID        int64
	EonPublicKey []byte
}

type MetaInf struct {
	Key   string
	Value string
}
