// Code generated by sqlc. DO NOT EDIT.
// source: query.sql

package snpdb

import (
	"context"

	"github.com/jackc/pgconn"
)

const getDecryptionKey = `-- name: GetDecryptionKey :one
SELECT epoch_id, key
FROM decryption_key
WHERE epoch_id = $1
`

func (q *Queries) GetDecryptionKey(ctx context.Context, epochID []byte) (DecryptionKey, error) {
	row := q.db.QueryRow(ctx, getDecryptionKey, epochID)
	var i DecryptionKey
	err := row.Scan(&i.EpochID, &i.Key)
	return i, err
}

const getEonPublicKey = `-- name: GetEonPublicKey :one
SELECT eon_public_key
FROM eon_public_key
WHERE eon_id = $1
`

func (q *Queries) GetEonPublicKey(ctx context.Context, eonID int64) ([]byte, error) {
	row := q.db.QueryRow(ctx, getEonPublicKey, eonID)
	var eon_public_key []byte
	err := row.Scan(&eon_public_key)
	return eon_public_key, err
}

const getEonPublicKeyLatest = `-- name: GetEonPublicKeyLatest :one
SELECT eon_id, eon_public_key
FROM eon_public_key
ORDER BY eon_id DESC
LIMIT 1
`

func (q *Queries) GetEonPublicKeyLatest(ctx context.Context) (EonPublicKey, error) {
	row := q.db.QueryRow(ctx, getEonPublicKeyLatest)
	var i EonPublicKey
	err := row.Scan(&i.EonID, &i.EonPublicKey)
	return i, err
}

const insertDecryptionKey = `-- name: InsertDecryptionKey :execresult
INSERT INTO decryption_key (
        epoch_id,
        key
) VALUES (
        $1, $2
)
ON CONFLICT DO NOTHING
`

type InsertDecryptionKeyParams struct {
	EpochID []byte
	Key     []byte
}

func (q *Queries) InsertDecryptionKey(ctx context.Context, arg InsertDecryptionKeyParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, insertDecryptionKey, arg.EpochID, arg.Key)
}

const insertEonPublicKey = `-- name: InsertEonPublicKey :exec
INSERT INTO eon_public_key (
        eon_id,
        eon_public_key
) VALUES (
        $1, $2
)
ON CONFLICT DO NOTHING
`

type InsertEonPublicKeyParams struct {
	EonID        int64
	EonPublicKey []byte
}

func (q *Queries) InsertEonPublicKey(ctx context.Context, arg InsertEonPublicKeyParams) error {
	_, err := q.db.Exec(ctx, insertEonPublicKey, arg.EonID, arg.EonPublicKey)
	return err
}
