// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package chainobsdb

import ()

type EventSyncProgress struct {
	ID              bool  `db:"id"`
	NextBlockNumber int32 `db:"next_block_number"`
	NextLogIndex    int32 `db:"next_log_index"`
}
