// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package chainobsdb

import ()

type EventSyncProgress struct {
	ID              bool
	NextBlockNumber int32
	NextLogIndex    int32
}
