// Package kproapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.1 DO NOT EDIT.
package kproapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// DecryptionKey defines model for DecryptionKey.
type DecryptionKey string

// DecryptionTrigger defines model for DecryptionTrigger.
type DecryptionTrigger struct {
	BlockNumber uint64 `json:"block_number"`
	EpochId     string `json:"epoch_id"`
}

// Eon defines model for Eon.
type Eon struct {
	ActivationBlockNumber int    `json:"activation_block_number"`
	EonKey                string `json:"eon_key"`
	Finished              bool   `json:"finished"`
	Index                 int    `json:"index"`
	Successful            bool   `json:"successful"`
}

// Eons defines model for Eons.
type Eons []Eon

// EpochID defines model for EpochID.
type EpochID string

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// SubmitDecryptionTriggerJSONBody defines parameters for SubmitDecryptionTrigger.
type SubmitDecryptionTriggerJSONBody DecryptionTrigger

// SubmitDecryptionTriggerJSONRequestBody defines body for SubmitDecryptionTrigger for application/json ContentType.
type SubmitDecryptionTriggerJSONRequestBody SubmitDecryptionTriggerJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /decryptionKey/{eon}/{epochID})
	GetDecryptionKey(w http.ResponseWriter, r *http.Request, eon int, epochID EpochID)

	// (POST /decryptionTrigger)
	SubmitDecryptionTrigger(w http.ResponseWriter, r *http.Request)

	// (GET /eons)
	GetEons(w http.ResponseWriter, r *http.Request)

	// (GET /ping)
	Ping(w http.ResponseWriter, r *http.Request)

	// (POST /shutdown)
	Shutdown(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.HandlerFunc) http.HandlerFunc

// GetDecryptionKey operation middleware
func (siw *ServerInterfaceWrapper) GetDecryptionKey(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "eon" -------------
	var eon int

	err = runtime.BindStyledParameter("simple", false, "eon", chi.URLParam(r, "eon"), &eon)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eon", Err: err})
		return
	}

	// ------------- Path parameter "epochID" -------------
	var epochID EpochID

	err = runtime.BindStyledParameter("simple", false, "epochID", chi.URLParam(r, "epochID"), &epochID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "epochID", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDecryptionKey(w, r, eon, epochID)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// SubmitDecryptionTrigger operation middleware
func (siw *ServerInterfaceWrapper) SubmitDecryptionTrigger(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitDecryptionTrigger(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetEons operation middleware
func (siw *ServerInterfaceWrapper) GetEons(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEons(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// Ping operation middleware
func (siw *ServerInterfaceWrapper) Ping(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Ping(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// Shutdown operation middleware
func (siw *ServerInterfaceWrapper) Shutdown(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Shutdown(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/decryptionKey/{eon}/{epochID}", wrapper.GetDecryptionKey)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/decryptionTrigger", wrapper.SubmitDecryptionTrigger)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/eons", wrapper.GetEons)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ping", wrapper.Ping)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/shutdown", wrapper.Shutdown)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xV32vjRhD+V5bpQV8US3cXAtXblYRiSuEgeUvTsJZG1l6kWXV3lIsx+t/LrORYsmVf",
	"r/Qgbyvtzo/vm29mtpDZurGExB7SLfisxFqH4zVmbtOwsfQ7buRHo5nREaTwV/Jyn1z8oi+Kh+3VZfcO",
	"IuBNg5CCZ2doDV00Mr9zZr1GF1w426BjgyHCqrLZ0yO19aq/LayrNUMKrSG+utx7NcQoHroIsLFZ+Wjy",
	"702oi8Dh361xmEN6v3cTTbN4eDW0qy+YsYS8sXScu87YPGuB93gIozZk6raGNJkFYOnx6Ryh76/mCS0M",
	"GV9iQD5crqytUJPcGsrx5dvRfZtl6H3RVnNuDkjqfUYnse7BjLKbxDhBZ2DQMNbh8M5hASn8FO+lGA86",
	"jIX77tWJdk5vgg8p3/L6+1V545ydUWJmc5wo0BB//DArwBq912sc0XdCYsHn/v0xFV0oW2H7BIh1xnIk",
	"XQevZSvALgj5q3VPEEHrKkihZG7SOB6uF8N1LKnl6DNnQs9BCnel8ar/tUKvuETlbFUZWqvB+GevnnDT",
	"oFOfPi8hgspkSB5HSfyxvAv0G67k88B+sIYIntH5PmqyeL9IxMY2SLoxkMLHRbJIIJJKlYHtOB+PlniL",
	"lrp4i31NO3mxxkDFFNBvyAHF3loSUIV1SpMK5mp5DSG0C3Jd5r3ZdJRJJk7XyOg8pPeHYW4sKVvMRWKr",
	"JDGpGqQBDkQ7ptASjOvPrsVoGKffassuOsphAPNfEhla41wyZztusO+6B3HhG0u+b5IPSbKTKlKoj26a",
	"ymSB6viL78fkv4syrUhohUP1HqIWUV0ml8e6QOlpZWaZKrVXZFmtEEmtkUQYmKsNct8whW4r/t9Q9dNl",
	"Bk1L+NJgJqFx96aLxo0wXpLWz6h/eHAIcMAkn+NGOOqC23ZVGz5eyr1M0POvNt/8gPLu4syQ8mmMhQd4",
	"vsHMFBuZMn1Ha8pV2DrqdetMhd3Ny3Qaa9hJb6LoOCzAk0NOloLsIeFFr2zLSleV8qwdY/4nzU24sFR/",
	"YL8G/zMYl+dSVQHpW6C8kQV9ivLPhtb9fvTontHNMCxPpvRSW1XBtezC3H6l0517W7as5Mk+xlwVb3eO",
	"ZuJ03T8BAAD//w/qbpapCwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
