x-logging: &logging
  driver: local
  options:
    max-file: 10

services:
  rs-build:
    build:
      dockerfile: docker/build-src/rolling-shutter/Dockerfile
      context: ..
    image: rolling-shutter
    command: "-v"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      start_period: "30s"
      start_interval: "2s"
    logging: *logging

  blockchain:
    build:
      dockerfile: docker-service/build-src/setup-blockchain/Dockerfile
      context: ..
    restart: always
    volumes:
      - ./data/geth:/data
    # currently health checks fail
    healthcheck:
      test: >
        curl -sSf -X POST http://127.0.0.1:8545 -H "Content-Type: application/json" --data-raw '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[], "id": 1}' | grep -o '"result":"0x'
      start_period: "30s"
      start_interval: "2s"
    logging: *logging

  deploy-contracts:
    build:
      dockerfile: docker-service/build-src/deploy_contracts/Dockerfile
      context: ..
    command:
      - "./script/Deploy.service.s.sol"
      - "--rpc-url"
      - "http://blockchain:8545"
      - "--broadcast"
    environment:
      DEPLOY_KEY: ${DEPLOY_KEY}
      PRIVATE_KEY: ${DEPLOY_KEY}
      # DEPLOY_CONF: /config/node-deploy.json
      # KEYPER_SET_INDEX: 0
    volumes:
      - ./data/deployments:/contracts/deployments
      - ./config:/config
    depends_on:
      - blockchain
    logging: *logging

  chain-0-validator:
    image: rolling-shutter
    restart: always
    entrypoint:
      - /rolling-shutter
      - chain
    volumes:
      - ./data/chain-0-validator:/chain
      - ./data/deployments:/deployments
    command: "--config /chain/config/config.toml"
    depends_on:
      - deploy-contracts
    logging: *logging

  chain-1-validator:
    image: rolling-shutter
    restart: always
    entrypoint:
      - /rolling-shutter
      - chain
    volumes:
      - ./data/chain-1-validator:/chain
      - ./data/deployments:/deployments
    command: "--config /chain/config/config.toml"
    depends_on:
      - deploy-contracts
    logging: *logging

  chain-2-validator:
    image: rolling-shutter
    restart: always
    entrypoint:
      - /rolling-shutter
      - chain
    volumes:
      - ./data/chain-2-validator:/chain
      - ./data/deployments:/deployments
    command: "--config /chain/config/config.toml"
    depends_on:
      - deploy-contracts
    logging: *logging

  chain-seed:
    image: rolling-shutter
    restart: always
    entrypoint:
      - /rolling-shutter
      - chain
    volumes:
      - ./data/chain-seed:/chain
    command: "--config /chain/config/config.toml"
    logging: *logging

  bootnode-0:
    image: rolling-shutter
    restart: always
    entrypoint:
      - /rolling-shutter
      - opbootstrap
    command: "--config /config/bootstrap.toml"
    volumes:
      - ./config:/config
      - ./data/deployments:/deployments
    depends_on:
      db:
        condition: service_healthy
    logging: *logging

  keyper-0:
    image: rolling-shutter
    restart: always
    entrypoint:
      - /rolling-shutter
      - "--loglevel=:debug,basichost:info,swarm:info,swarm2:info,net/identify:info,pubsub:info,p2p-config:info,upgrader:info"
      - snapshotkeyper
    command: "--config /config/keyper-0.toml"
    volumes:
      - ./config:/config
      - ./data/deployments:/deployments
    ports:
      - "9200:9100"
    depends_on:
      - db:
          condition: service_healthy
      - bootnode-0:
          condition: service_started
      - chain-0-validator
    logging: *logging

  keyper-1:
    image: rolling-shutter
    restart: always
    entrypoint:
      - /rolling-shutter
      - "--loglevel=:debug,basichost:info,swarm:info,swarm2:info,net/identify:info,pubsub:info,p2p-config:info,upgrader:info"
      - snapshotkeyper
    command: "--config /config/keyper-1.toml"
    volumes:
      - ./config:/config
      - ./data/deployments:/deployments
    ports:
      - "9201:9100"
    depends_on:
      - db:
          condition: service_healthy
      - bootnode-0:
          condition: service_started
      - chain-1-validator
    logging: *logging

  keyper-2:
    image: rolling-shutter
    restart: always
    entrypoint:
      - /rolling-shutter
      - "--loglevel=:debug,basichost:info,swarm:info,swarm2:info,net/identify:info,pubsub:info,p2p-config:info,upgrader:info"
      - snapshotkeyper
    command: "--config /config/keyper-2.toml"
    volumes:
      - ./config:/config
      - ./data/deployments:/deployments
    ports:
      - "9202:9100"
    depends_on:
      - db:
          condition: service_healthy
      - bootnode-0:
          condition: service_started
      - chain-2-validator
    logging: *logging

  dummyserver:
    build:
      dockerfile: docker/build-src/dummyserver/Dockerfile
      context: ..
    restart: always
    profiles:
      - dev
    logging: *logging

  dockerize:
    image: jwilder/dockerize
    profiles:
      - script
    logging: *logging
