// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.1 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// Eon defines model for Eon.
type Eon struct {
	ActivationBlockNumber int64    `json:"activation_block_number"`
	Eon                   int64    `json:"eon"`
	EonPublicKey          []byte   `json:"eon_public_key"`
	InstanceId            int64    `json:"instance_id"`
	KeyperConfigIndex     int64    `json:"keyper_config_index"`
	Signatures            [][]byte `json:"signatures"`
}

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// NextEpoch defines model for NextEpoch.
type NextEpoch struct {
	Id []byte `json:"id"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	EncryptedTx string `json:"encrypted_tx"`
	Epoch       []byte `json:"epoch"`
}

// TransactionId defines model for TransactionId.
type TransactionId struct {
	Id []byte `json:"id"`
}

// GetEonPublicKeyParams defines parameters for GetEonPublicKey.
type GetEonPublicKeyParams struct {
	// Upper bound for block near the activation block for queried Eon
	ActivationBlock int64 `json:"activation_block"`
}

// SubmitTransactionJSONBody defines parameters for SubmitTransaction.
type SubmitTransactionJSONBody Transaction

// SubmitTransactionJSONRequestBody defines body for SubmitTransaction for application/json ContentType.
type SubmitTransactionJSONRequestBody SubmitTransactionJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /eon)
	GetEonPublicKey(w http.ResponseWriter, r *http.Request, params GetEonPublicKeyParams)

	// (GET /next-epoch)
	GetNextEpoch(w http.ResponseWriter, r *http.Request)

	// (GET /ping)
	Ping(w http.ResponseWriter, r *http.Request)

	// (POST /tx)
	SubmitTransaction(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.HandlerFunc) http.HandlerFunc

// GetEonPublicKey operation middleware
func (siw *ServerInterfaceWrapper) GetEonPublicKey(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEonPublicKeyParams

	// ------------- Required query parameter "activation_block" -------------
	if paramValue := r.URL.Query().Get("activation_block"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "activation_block"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "activation_block", r.URL.Query(), &params.ActivationBlock)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "activation_block", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEonPublicKey(w, r, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetNextEpoch operation middleware
func (siw *ServerInterfaceWrapper) GetNextEpoch(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNextEpoch(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// Ping operation middleware
func (siw *ServerInterfaceWrapper) Ping(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Ping(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// SubmitTransaction operation middleware
func (siw *ServerInterfaceWrapper) SubmitTransaction(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitTransaction(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/eon", wrapper.GetEonPublicKey)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/next-epoch", wrapper.GetNextEpoch)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ping", wrapper.Ping)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/tx", wrapper.SubmitTransaction)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xVXYvjNhT9K0It9MUTp7ulD3lrIZShtAx0+rRdgizfONrYV9qr6+mYxf+9SPKMP+Jh",
	"U9iBeUos3Y9zj46OvkhtG2cRkL3cfZFen6BR8e/eYvhxZB0QG4iLSrN5UGwsHora6vMB26YACltHS41i",
	"uZMG+eefZCa5c5A+oQKSfSYhlbwu8uDaojb6cIZullR0DGOOZzJYhRSDnhVqOJjyyiZn6BzQQVs8mupg",
	"sITHKzO9qVBxS4kUw9D4qzAOC4pIdbLvM0nwuTUEpdx9mA1wwUD2IvXrcySyZ0g/Pve3xSfQHADtiSxd",
	"HrO2JSypeP9ulYoGvFdVjF6Muxgv1hzj19D8CY+8d1afLhEtDnWd4CWh5WqXe1LoA5trAgfU1DmG8sBz",
	"MQw9Vg4VnhD/P3QpLZt3/Are2/IVmenjJTraJABkpTn8RdXESqeWGegGgf+1dJaZbKmWO3lidrs8H7Y3",
	"w3YegJfgNRmXiJb3J+NFWirACz6BIFvXBisxJP/ghbZ1rdiS+OXuVrAVvi0aw4JHCrzMZG00oIcJuj9u",
	"7+P9MlyHz0Xh57Iykw9APgHabn7cbEOWdYDKGbmT7zfbzVZm0ik+RXLzwbIqiFzMJ/oNWOwt3sVb+jt0",
	"4mhJKAxrMlYl9XRoIXYaGnuQaoCBvNx9WJb+2zkgUdgWy1g13niBoCgSN3rBsBNiPrdABsqhvQllwlLo",
	"NbC0tBA5VQVTC9nwAFxlg/3HkO6dRZ+U+G67fdIOYORLOVcbHTvmn3yicuzwPcFR7uR3+fgG5cMDlIch",
	"oiLnvOwtiqDRAC1Mr7AUqq5FskAvgt1BKZJx3pyhE4PfeBEuhgAMNlQmdR5VW/O3QxytdAVzi/DoQDOU",
	"Ap5i+kzmCI9882weLypsNm5hW44KCMkiJv+zKrbRSl/xkMYmK2PffgX3mzgDF9zxJfbvDFbJqDzQA9AK",
	"03fpTZgwjG1dx9Lp/XDWr1T+K9maQvHs/lOPu2iT4u9nEeHmgudfbdl9M/6mHVZYnGyP5nxhIv0rKm7+",
	"Fq5AnLAozBu4533/XwAAAP//ZJSS9GMLAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
