// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.1 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// Eon defines model for Eon.
type Eon struct {
	ActivationBlockNumber int64    `json:"activation_block_number"`
	EonPublicKey          []byte   `json:"eon_public_key"`
	SignedMessages        [][]byte `json:"signed_messages"`
}

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// NextEpoch defines model for NextEpoch.
type NextEpoch struct {
	Id []byte `json:"id"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	EncryptedTx []byte `json:"encrypted_tx"`
	Epoch       []byte `json:"epoch"`
}

// TransactionId defines model for TransactionId.
type TransactionId struct {
	Id []byte `json:"id"`
}

// GetEonPublicKeyMessagesParams defines parameters for GetEonPublicKeyMessages.
type GetEonPublicKeyMessagesParams struct {
	// Upper bound for block near the activation block for queried Eon
	ActivationBlock int64 `json:"activation_block"`
}

// SubmitTransactionJSONBody defines parameters for SubmitTransaction.
type SubmitTransactionJSONBody Transaction

// SubmitTransactionJSONRequestBody defines body for SubmitTransaction for application/json ContentType.
type SubmitTransactionJSONRequestBody SubmitTransactionJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /eon)
	GetEonPublicKeyMessages(w http.ResponseWriter, r *http.Request, params GetEonPublicKeyMessagesParams)

	// (GET /next-epoch)
	GetNextEpoch(w http.ResponseWriter, r *http.Request)

	// (GET /ping)
	Ping(w http.ResponseWriter, r *http.Request)

	// (POST /tx)
	SubmitTransaction(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.HandlerFunc) http.HandlerFunc

// GetEonPublicKeyMessages operation middleware
func (siw *ServerInterfaceWrapper) GetEonPublicKeyMessages(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEonPublicKeyMessagesParams

	// ------------- Required query parameter "activation_block" -------------
	if paramValue := r.URL.Query().Get("activation_block"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "activation_block"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "activation_block", r.URL.Query(), &params.ActivationBlock)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "activation_block", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEonPublicKeyMessages(w, r, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetNextEpoch operation middleware
func (siw *ServerInterfaceWrapper) GetNextEpoch(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNextEpoch(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// Ping operation middleware
func (siw *ServerInterfaceWrapper) Ping(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Ping(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// SubmitTransaction operation middleware
func (siw *ServerInterfaceWrapper) SubmitTransaction(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitTransaction(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/eon", wrapper.GetEonPublicKeyMessages)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/next-epoch", wrapper.GetNextEpoch)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ping", wrapper.Ping)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/tx", wrapper.SubmitTransaction)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xV34vjNhD+V4Ra6Is3Tu9KH/zWQiihXFlo+nQ9gmxPEl3skW403sYc/t+LJCe2Ey+X",
	"g13Yp8TS/Pjmm5lPX2VhamsQkJ3MvkpXHKBW4e/KoP+xZCwQawiHqmD9pFgb3OaVKY5bbOocyF/tDNWK",
	"ZSY18q+/yERyayF+wh5IdokEg1vb5JUutkdoJ055yzD4OCaNe+/i9B6h3NbgnNpHDJqhdnc59weKSLWy",
	"6xJJ8KXRBKXMPt5ETp4t7gb4p0tok3+Ggn2uFZGhW8IKU8I1O+/fzbLTI/HWV5VcIQ8xB/s5NH/BiVfW",
	"FIdbRLq8g7urjLqczbIhhc6zNjcqgAW1lqHc8umubsEZ7/dhi27JNN830K7LV+TFG2ncmdh+ZFWw/4uq",
	"DpEODTPQAwL/Z+goE9lQJTN5YLZZmvbXi/469cBLcAVpG2mWm4N2Ih7l4AQfQJCpKo170Tv/5ERhqkqx",
	"IfHb41qwEa7Ja82CBwr8wFe6AHQwQvdhvQmLo7nyn1eBL2FlIp+AXAS0XPy8WHovYwGV1TKT7xfLxVIm",
	"0io+BHJTiCOyh8DFtKI/gIWqKrEy+BiW7E9oxXkvxc6QUOgvZUhB6txB7zj2+TCsslWkamAgJ7OP1/n+",
	"sRZI5KbBMkQPyy4QFAU2Bxnob7zNlwZIQ9nD0D6MP2plcqbuWj3keFSYGkh6db1LLLtP3t1Zgy6O57vl",
	"8jxQgIFEZW2li5Ax/ewiv0OGHwl2MpM/pIPAp726p76IMKZTXlYGhR9cD81Xr7AMfTlCa4GciIopohA+",
	"HMdN8tsiAL0ylXFkd6qp+OUQB3WdwdwgnCwUDKWAs02XyBThxA8XRXl27Cbl5qbhMAHeWQTnf2eHblDX",
	"V2zSkGSm7PU3cL+JHlgvmc+x/6hxH9XLAT0BzTDtTaYMY1NVIXR8UqxxM5H/jlqnUFyehLHw3aSJ9puJ",
	"hd9ccPy7KdsX42+cYYbF0fWg2Dci0r3ixE0fyBmIIxaFfgN73nX/BwAA//9IRxx3wAoAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
