openapi: "3.0.0"
info:
  version: 0.1.0
  title: rolling shutter collator
  description: This describes the rolling shutter's collator API to submit transactions
  contact:
    name: shutter-network
    url: http://shutter.network/
  license:
    name: MIT
paths:
  /ping:
    get:
      description: |
        Pings the server
      operationId: ping
      parameters:
  /next-epoch:
    get:
      description: |
        Get information about the next epoch
      operationId: getNextEpoch
      parameters:
      responses:
        "200":
          description: Information about the next epoch
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NextEpoch"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /eon:
    get:
      description: Get EonPublicKey for an Eon
      operationId: GetEonPublicKey
      parameters:
        - name: activation_block
          in: query
          description: Upper bound for block near the activation block for queried Eon
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Eon information and all keypers signed public-key messages byte encoded
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Eon"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /tx:
    post:
      description: Submit an encrypted transaction
      operationId: SubmitTransaction
      requestBody:
        description: Transaction to submit
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Transaction"
      responses:
        "200":
          description: transaction id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionId"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Transaction:
      type: object
      required:
        - epoch
        - encrypted_tx
      properties:
        epoch:
          type: string
          format: byte
        encrypted_tx:
          type: string
          format: byte
    TransactionId:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          format: byte
    NextEpoch:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          format: byte
    Eon:
      type: object
      required:
        - instance_id
        - eon_public_key
        - activation_block_number
        - keyper_config_index
        - eon
        - signatures
      properties:
        instance_id:
          type: integer
          format: int64
        eon_public_key:
          type: string
          format: byte
        activation_block_number:
          type: integer
          format: int64
        keyper_config_index:
          type: integer
          format: int64
        eon:
          type: integer
          format: int64
        signatures:
          type: array
          items:
            type: string
            format: byte
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
