// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type DecryptionKey struct {
	Eon           int64
	EpochID       []byte
	DecryptionKey []byte
}

type DecryptionKeyShare struct {
	Eon                int64
	EpochID            []byte
	KeyperIndex        int64
	DecryptionKeyShare []byte
}

type DecryptionTrigger struct {
	EpochID []byte
}

type DkgAccusation struct {
	KeyperConfigIndex int64
	RetryCounter      int64
	AccuserIndex      int64
	AccusedIndex      int64
}

type DkgApology struct {
	KeyperConfigIndex int64
	RetryCounter      int64
	ApologizerIndex   int64
	AccuserIndex      int64
	PolyEval          []byte
}

type DkgPolyCommitment struct {
	KeyperConfigIndex int64
	RetryCounter      int64
	KeyperIndex       int64
	Commitment        []byte
}

type DkgPolyEval struct {
	KeyperConfigIndex int64
	RetryCounter      int64
	SenderIndex       int64
	ReceiverIndex     int64
	EncryptedEval     []byte
}

type DkgResult struct {
	Eon        int64
	Success    bool
	Error      sql.NullString
	PureResult []byte
}

type EciesKey struct {
	KeyperAddress  string
	EciesPublicKey []byte
}

type Eon struct {
	Eon                   int64
	ActivationBlockNumber int64
	KeyperConfigIndex     int64
}

type LastBatchConfigSent struct {
	EnforceOneRow     bool
	KeyperConfigIndex int64
}

type LastBlockSeen struct {
	EnforceOneRow bool
	BlockNumber   int64
}

type OutgoingEonKey struct {
	EonPublicKey []byte
	Eon          int64
}

type PolyEval struct {
	Eon             int64
	ReceiverAddress string
	Eval            []byte
}

type Puredkg struct {
	Eon     int64
	Puredkg []byte
}

type TendermintBatchConfig struct {
	KeyperConfigIndex     int32
	Height                int64
	Keypers               []string
	Threshold             int32
	Started               bool
	ActivationBlockNumber int64
}

type TendermintEncryptionKey struct {
	Address             string
	EncryptionPublicKey []byte
	Height              int64
}

type TendermintOutgoingMessage struct {
	ID          int32
	Description string
	Msg         []byte
}

type TendermintSyncMetum struct {
	CurrentBlock        int64
	LastCommittedHeight int64
	SyncTimestamp       time.Time
}
