// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"

	"github.com/jackc/pgtype"
)

type DecryptionKey struct {
	Eon           int64
	EpochID       []byte
	DecryptionKey []byte
}

type DecryptionKeyShare struct {
	Eon                int64
	EpochID            []byte
	KeyperIndex        int64
	DecryptionKeyShare []byte
}

type DecryptionTrigger struct {
	EpochID []byte
}

type DkgAccusation struct {
	KeyperConfigIndex int64
	RetryCounter      int64
	AccuserIndex      int64
	AccusedIndex      int64
}

type DkgApology struct {
	KeyperConfigIndex int64
	RetryCounter      int64
	ApologizerIndex   int64
	AccuserIndex      int64
	PolyEval          []byte
}

type DkgInitialState struct {
	KeyperConfigIndex int64
	RetryCounter      int64
	PuredkgBytes      []byte
}

type DkgPolyCommitment struct {
	KeyperConfigIndex int64
	RetryCounter      int64
	KeyperIndex       int64
	Commitment        []byte
}

type DkgPolyEval struct {
	KeyperConfigIndex int64
	RetryCounter      int64
	SenderIndex       int64
	ReceiverIndex     int64
	EncryptedEval     []byte
}

type DkgResult struct {
	Eon        int64
	Success    bool
	Error      sql.NullString
	PureResult []byte
}

type EciesKey struct {
	KeyperAddress  string
	EciesPublicKey []byte
}

type Eon struct {
	Eon                   int64
	ActivationBlockNumber int64
	KeyperConfigIndex     int64
	DkgContract           sql.NullString
	PhaseLength           sql.NullInt64
	LeadLength            sql.NullInt64
}

type TxOutbox struct {
	ID        int64
	ToAddress string
	Data      []byte
	Value     pgtype.Numeric
	Status    string
	TxHash    sql.NullString
	Nonce     sql.NullInt64
	Error     sql.NullString
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	Label     string
}
