#!/usr/bin/env -S uv run --script
#MISE description="Start the implemented docker3 stack"
#MISE depends=["init-keyper-dbs", "fund-keypers"]

import utils


utils.run(["docker", "compose", "up", "-d"])

utils.wait_for_service_health("ethereum")
utils.wait_for_service_health("db")
