#!/usr/bin/env -S uv run --script
# fmt: off
#MISE description="Run Ethereum and wait for RPC readiness"
#MISE depends=["gen-compose"]
# fmt: on

import utils

utils.run(["docker", "compose", "up", "-d", "ethereum"])
utils.wait_for_service_health("ethereum")
