#!/usr/bin/env -S uv run --script
#MISE description="Wait for the initial DKG to succeed"
#MISE depends=["up", "add-initial-keyper-set"]

import utils

utils.run(["mise", "run", "wait-for-dkg", "--keyper-set-index", "1"])
