
# Peer identity: /p2p/12D3KooWQ8iKQe4iEfkTh3gdBtpxWsKwx3BwrA18km5rq3Zwt2QF
# Ethereum address: 0xCDD50A6F9B1439dc14c4f2A7eaF14dA1EF5A476c


InstanceID = 0
# If it's empty, we use the standard PG_ environment variables
DatabaseURL		= "postgres://postgres@db:5432/keyper-0"
HTTPEnabled = false
HTTPListenAddress = ':3000'

[P2P]
P2PKey = 'CAESQJ3NdZ6mRrDAW/Z59OKwcKdOCbZQ45z5o8K+tLHOL8Xw1LbawPZLk3mXNyiDyADcLk1bqYMe3uQ6T8xi65zkM0A='
ListenAddresses   = ["/ip4/0.0.0.0/tcp/23000"]
# Overwrite p2p boostrap nodes
CustomBootstrapAddresses  = [
    "/dns4/bootnode-0/tcp/23000/p2p/12D3KooWJN7262vmnEQHkYG7VrZDwz9fMyJtHyvGp4XSenuUYfeJ",
    "/dns4/bootnode-1/tcp/23000/p2p/12D3KooWSayB2PEYpXtdk2dEqFaagoy8kDzmWpoD9DieuuzYdcBo"
]

[Ethereum]
PrivateKey = '82904d1c48d3a27d218408fc2db3e743f554a69b05b91d28c2897a9026ea47df'
# The JSON RPC endpoint where the contracts are accessible
ContractsURL = 'http://127.0.0.1:8555/'
# Contract source directory
DeploymentDir       = "./deployments/dockerGeth/"
# The layer 1 JSON RPC endpoint
EthereumURL         = "http://geth:8545/"

[Shuttermint]
ShuttermintURL		= "http://chain-0-sentry:26657"
ValidatorPublicKey = '720accc33c2bce1319d12b5f23f81b39a33f487e21c4a4d7ca1e1f7954a24172'
DKGPhaseLength = 8
DKGStartBlockDelta = 200
