# Peer identity: /p2p/12D3KooWKm6Daxect5KtqgF7HeF1woSb16xQDGXThaKxtyngEHaG
# Ethereum address: 0x62F6DC5638250bD9edE84DFBfa54efA263186a4a

InstanceID = 42
DatabaseURL = "postgres:///keyper-db-2"
BeaconAPIURL = 'https://chiado-node.staging.shutter.network/consensus'
HTTPEnabled = true
HTTPListenAddress = ":24002"
MaxNumKeysPerMessage = 500

[P2P]
P2PKey = 'CAESQIaR6iJCaJcmXwNyze/UpmAvKK2yQybw+sH7OG9HKbeek74XSoI3XGj+ZLknktVJoxeSTf5fti/CX67DcHvZXOE='
ListenAddresses = ["/ip4/127.0.0.1/tcp/23102"]
CustomBootstrapAddresses = ['/ip4/127.0.0.1/tcp/2001/p2p/12D3KooWMyutShWdqYj7fre4Vjuq2QnCTb26Ki1KpyDyVsrmKeki']
Environment = "local"
DiscoveryNamespace = "shutter-42"

[P2P.FloodSubDiscovery]
enabled = false

[Gnosis]
EncryptedGasLimit = 1000000
MinGasPerTransaction = 21000
MaxTxPointerAge = 5
SecondsPerSlot = 5
SlotsPerEpoch = 16
GenesisSlotTimestamp = 1665396300
SyncStartBlockNumber = 0
SyncMonitorCheckInterval = 30

[Gnosis.Node]
PrivateKey = 'a4e901b1df81ff8fc5fa77f5bf0c15a4c8410e85fcaf19fbec47a2241b9d65d6'
ContractsURL = "https://chiado-node.staging.shutter.network/execution"
DeploymentDir = './deployments/localhost/'
EthereumURL = "wss://chiado-node.staging.shutter.network/execution"

[Gnosis.Contracts]
KeyperSetManager = '0x058062B7d74ba6B4Af1eE22833579C67adC17175'
KeyBroadcastContract = '0x74060a34F6ac647C29735A245617d36caD94d02C'
Sequencer = '0x62c70cf31AD1005944b66A2e539a11792D930998'
ValidatorRegistry = '0x716Be4F8C84989efF385277dad4f27B393330b99'
EonKeyPublish = '0xF087BfBC3D7820B23298f7a7b77387BfC55eD9C6'

[Shuttermint]
ShuttermintURL = 'http://localhost:26657'
ValidatorPublicKey = 'df359cd93fe4570db05afb626fd9055802834ed5ca1267ae288e1fd36ee69666'
EncryptionKey = 'ac12d8fbf00461be79021e378f230d5dd93ffa24eb156785a13c010d0809a633'
DKGPhaseLength = 8
DKGStartBlockDelta = 5

[Metrics]
Enabled = true
Host = '[::]'
Port = 9102
