// Code generated by "stringer -type=StateEnum -output stateenum_string.gen.go"; DO NOT EDIT.

package batch

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoState-0]
	_ = x[InitialState-1]
	_ = x[PendingState-2]
	_ = x[CommittedState-3]
	_ = x[DecryptedState-4]
	_ = x[ConfirmedState-5]
	_ = x[StoppingState-6]
}

const _StateEnum_name = "NoStateInitialStatePendingStateCommittedStateDecryptedStateConfirmedStateStoppingState"

var _StateEnum_index = [...]uint8{0, 7, 19, 31, 45, 59, 73, 86}

func (i StateEnum) String() string {
	if i < 0 || i >= StateEnum(len(_StateEnum_index)-1) {
		return "StateEnum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StateEnum_name[_StateEnum_index[i]:_StateEnum_index[i+1]]
}
