// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package snpdb

import ()

type DecryptionKey struct {
	EpochID []byte
	Key     []byte
}

type EonPublicKey struct {
	EonID        int64
	EonPublicKey []byte
}
