#! /usr/bin/env bash
set -euo pipefail

: "${GO:=go}"
: "${VERSION:=}"
: "${TARGETS:=linux-amd64 linux-arm linux-arm64 freebsd-amd64 openbsd-amd64 darwin-amd64}"

if [[ -z "${VERSION}" ]]; then
   VERSION=$(git describe --tags --always --abbrev=4 --dirty --match 'rolling-shutter/v*' | sed -e s#^rolling-shutter/##)
fi

git clean -xfd bin
for osarch in ${TARGETS}; do
    IFS='-' read -r os arch <<< "${osarch}"
    target=bin/rolling-shutter-${os}-${arch}-${VERSION}
    echo "Building ${target}"
    env GOARCH="${arch}" GOOS="${os}" ${GO} build -o "${target}" -ldflags "-X github.com/shutter-network/shutter/shuttermint/cmd/shversion.version=${VERSION}" .
done
